/* -------------------------------------------------------------------------- */
/*  DÉBROUILLE SERVER — GLOBAL BOOTSTRAP (WORLD #1 FINAL)                     */
/* -------------------------------------------------------------------------- */
/*  File: backend/src/server.ts                                               */
/* -------------------------------------------------------------------------- */

import http, { Server } from "http";
import crypto from "crypto";

/* -------------------------------------------------------------------------- */
/* EARLY ENV SAFETY BOOTSTRAP                                                 */
/* -------------------------------------------------------------------------- */
/**
 * ⚠️ IMPORTANT
 * Some critical env variables (JWT, secrets, etc.) are mandatory in production
 * but must not block local development or CI.
 *
 * This block guarantees:
 *  - DEV → safe autogenerated defaults
 *  - PROD → strict validation (crash if missing)
 */

function ensureEnv(
  key: string,
  options?: {
    devDefault?: () => string;
    sensitive?: boolean;
  }
) {
  if (process.env[key]) return;

  const isProd = process.env.NODE_ENV === "production";

  if (isProd) {
    throw new Error(
      `Missing required environment variable: ${key}`
    );
  }

  const value =
    options?.devDefault?.() ??
    `DEV_${key}_${crypto.randomBytes(8).toString("hex")}`;

  process.env[key] = value;

  // Never log sensitive values
  if (!options?.sensitive) {
    // eslint-disable-next-line no-console
    console.warn(
      `⚠️ [DEV] Auto-generated env ${key} = ${value}`
    );
  } else {
    // eslint-disable-next-line no-console
    console.warn(
      `⚠️ [DEV] Auto-generated sensitive env ${key}`
    );
  }
}

/**
 * Minimum required secrets for local boot.
 * Add here if new mandatory ENV appear later.
 */
ensureEnv("JWT_ACCESS_SECRET", {
  sensitive: true,
});
ensureEnv("JWT_REFRESH_SECRET", {
  sensitive: true,
});
ensureEnv("ENCRYPTION_SECRET", {
  sensitive: true,
});

/* -------------------------------------------------------------------------- */
/* CONFIG                                                                     */
/* -------------------------------------------------------------------------- */

import { ENV } from "./config/env";

/* -------------------------------------------------------------------------- */
/* DATABASE                                                                   */
/* -------------------------------------------------------------------------- */

import {
  initDatabase,
  shutdownDatabase,
  getDatabaseInfo,
} from "./database";

/* -------------------------------------------------------------------------- */
/* APPLICATION                                                                */
/* -------------------------------------------------------------------------- */

import { createApp } from "./app";

/* -------------------------------------------------------------------------- */
/* OBSERVABILITY                                                              */
/* -------------------------------------------------------------------------- */

import { logger } from "./shared/logger";

/* -------------------------------------------------------------------------- */
/* TYPES                                                                      */
/* -------------------------------------------------------------------------- */

type ShutdownSignal =
  | "SIGINT"
  | "SIGTERM"
  | "UNCAUGHT_EXCEPTION"
  | "UNHANDLED_REJECTION";

/* -------------------------------------------------------------------------- */
/* RUNTIME STATE                                                              */
/* -------------------------------------------------------------------------- */

let server: Server | undefined;
let shuttingDown = false;
const SHUTDOWN_TIMEOUT_MS = 15_000;

/* -------------------------------------------------------------------------- */
/* INFRA INITIALIZATION                                                       */
/* -------------------------------------------------------------------------- */

const initializeInfrastructure = async (): Promise<void> => {
  logger.info("🗄️ Initializing database...");
  await initDatabase();

  const dbInfo = getDatabaseInfo();

  // ✅ Normalized structured log payload
  logger.info("✅ Database ready", {
    db: dbInfo,
  });
};

/* -------------------------------------------------------------------------- */
/* SERVER STARTUP                                                             */
/* -------------------------------------------------------------------------- */

const startHttpServer = async (): Promise<Server> => {
  logger.info("🧠 Creating application instance...");
  const app = createApp();

  logger.info("🌐 Creating HTTP server...");
  const httpServer = http.createServer(app);

  await new Promise<void>((resolve, reject) => {
    httpServer.once("error", reject);
    httpServer.listen(ENV.PORT, () => resolve());
  });

  logger.info("🚀 Server is LIVE", {
    port: ENV.PORT,
    env: ENV.NODE_ENV,
    pid: process.pid,
  });

  return httpServer;
};

/* -------------------------------------------------------------------------- */
/* BOOTSTRAP                                                                  */
/* -------------------------------------------------------------------------- */

const bootstrap = async (): Promise<void> => {
  const startedAt = Date.now();

  try {
    logger.info("⚙️ Bootstrapping Debrouille Backend...");

    await initializeInfrastructure();
    server = await startHttpServer();

    const durationMs = Date.now() - startedAt;

    logger.info("✅ Backend successfully started", {
      startupTimeMs: durationMs,
    });
  } catch (error) {
    logger.fatal("🔥 Fatal error during bootstrap", {
      error,
    });
    process.exit(1);
  }
};

/* -------------------------------------------------------------------------- */
/* GRACEFUL SHUTDOWN                                                          */
/* -------------------------------------------------------------------------- */

const shutdown = async (signal: ShutdownSignal): Promise<void> => {
  if (shuttingDown) return;
  shuttingDown = true;

  const shutdownStartedAt = Date.now();

  logger.warn("⚠️ Shutdown initiated", {
    signal,
  });

  const forceExitTimeout = setTimeout(() => {
    logger.error("⏱️ Forced shutdown timeout exceeded");
    process.exit(1);
  }, SHUTDOWN_TIMEOUT_MS);

  try {
    /* ====================================================================== */
    /* STOP HTTP SERVER                                                       */
    /* ====================================================================== */

    if (server) {
      logger.info("🛑 Closing HTTP server...");
      await new Promise<void>((resolve, reject) => {
        server!.close((err) => {
          if (err) reject(err);
          else resolve();
        });
      });
    }

    /* ====================================================================== */
    /* DATABASE SHUTDOWN                                                      */
    /* ====================================================================== */

    logger.info("🗄️ Closing database...");
    await shutdownDatabase();

    const durationMs = Date.now() - shutdownStartedAt;

    logger.info("✅ Graceful shutdown completed", {
      durationMs,
    });

    clearTimeout(forceExitTimeout);
    process.exit(0);
  } catch (error) {
    logger.error("❌ Error during shutdown", {
      error,
    });
    clearTimeout(forceExitTimeout);
    process.exit(1);
  }
};

/* -------------------------------------------------------------------------- */
/* PROCESS SIGNAL HANDLERS                                                    */
/* -------------------------------------------------------------------------- */

process.on("SIGINT", () => shutdown("SIGINT"));
process.on("SIGTERM", () => shutdown("SIGTERM"));

process.on("uncaughtException", (error) => {
  logger.fatal("🔥 Uncaught exception", {
    error,
  });
  shutdown("UNCAUGHT_EXCEPTION");
});

process.on("unhandledRejection", (reason) => {
  logger.fatal("🔥 Unhandled promise rejection", {
    reason,
  });
  shutdown("UNHANDLED_REJECTION");
});

/* -------------------------------------------------------------------------- */
/* START APPLICATION                                                          */
/* -------------------------------------------------------------------------- */

bootstrap().catch((error) => {
  logger.fatal("🔥 Bootstrap promise rejected", {
    error,
  });
  process.exit(1);
});
